### ISSUE TITLE
Paragraph text is indenting by default

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/ppb-live-editor#12]
See screenshot

![screen shot 2016-01-12 at 19 17 09](https://cloud.githubusercontent.com/assets/3070779/12274100/287d26a0-b961-11e5-8530-4e2604791a8d.png)

**Comment by shramee** [comment]
It was because rag adjust was being loaded even in live edit...
And One space before each para got piled up after saving and publishing again and again...

No more spaces will be added now ;) But existing spaces will have to be manually removed...
