### ISSUE TITLE
Row styling setting not working

### ISSUE THREAD

**Issue by shramee** [pootlepress/ppb-live-editor#4]
Row styling dialog doesn't save values and also doesn't show color fields etc.

**Comment by jamiemarsland** [comment]
This still isn't quite working, when you back to the front screen the row background is not showing..see screenshot

![screen shot 2016-01-12 at 19 24 13](https://cloud.githubusercontent.com/assets/3070779/12274289/24728f18-b962-11e5-867b-319d69ec2934.png)

**Comment by shramee** [comment]
Hmm... seems to happen with full width rows for me...
